spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jamie_bookshop
    password: jamie
    username: jamie123
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update